/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalDatenschutzRouteImport } from './routes/legal/datenschutz'
import { Route as LegalAgbRouteImport } from './routes/legal/agb'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDatenschutzRoute = LegalDatenschutzRouteImport.update({
  id: '/legal/datenschutz',
  path: '/legal/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAgbRoute = LegalAgbRouteImport.update({
  id: '/legal/agb',
  path: '/legal/agb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/device'
    | '/login'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/device'
    | '/login'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/device'
    | '/login'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  LegalAgbRoute: typeof LegalAgbRoute
  LegalDatenschutzRoute: typeof LegalDatenschutzRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/datenschutz': {
      id: '/legal/datenschutz'
      path: '/legal/datenschutz'
      fullPath: '/legal/datenschutz'
      preLoaderRoute: typeof LegalDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/agb': {
      id: '/legal/agb'
      path: '/legal/agb'
      fullPath: '/legal/agb'
      preLoaderRoute: typeof LegalAgbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  LegalAgbRoute: LegalAgbRoute,
  LegalDatenschutzRoute: LegalDatenschutzRoute,
  LegalImpressumRoute: LegalImpressumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
